# -*- coding: utf-8 -*-
"""
services/match_service.py

职责：
- 输入：words(list[str]) + selected_fields(list[str]) + cache_mode
- 输出：每个 word 对应一个选中的 Entry（可能字段不全） + missing_fields
- 规则：
  1) 优先 global_cache 命中且满足字段
  2) 否则查 uploaded_vocab_cache：多 entry 用 tie-break 选 best
  3) 都不满足则标记 need_enrich（并返回缺失字段）
- 写回策略：
  - USE_CACHE：只填空，不覆盖已有值
  - FORCE_OVERWRITE：整条覆盖（作为“强制重生成”）
  - TEMP_ONLY：仅本次生效，不写回 global_cache
"""

from __future__ import annotations

import json
import os
import random
import re
from dataclasses import dataclass
from typing import Any, Dict, List, Optional, Tuple

from core.entry_schema import Entry, WordEntryGroup
import logging
from core.file_lock import file_lock

logger = logging.getLogger(__name__)

# =========================
# CacheMode（前端勾选映射）
# =========================

class CacheMode:
    USE_CACHE = "USE_CACHE"               # 默认：允许写回填空
    FORCE_OVERWRITE = "FORCE_OVERWRITE"   # 强制重生成（写回覆盖）
    TEMP_ONLY = "TEMP_ONLY"               # 仅本次生效（不写回）


# =========================
# 字段集合（和 entry_schema 对齐）
# =========================
VALID_FIELDS = {
    "word_original",
    "word_norm",
    "phonetic_uk",
    "phonetic_us",
    "pos_cn",
    "definition_en",
    "example",
    "example_cn",
    "synonyms",
    # audio
    "audio_uk",
    "audio_us",
    "audio_primary",
}

ALLOWED_COUNTS = {15, 20, 25, 30, 50}

# ---- audio fields: system-level fields (NOT generated by DS) ----
AUDIO_FIELDS = {"audio_uk", "audio_us", "audio_primary"}

def norm_word(s: str) -> str:
    s = (s or "").strip()
    s = re.sub(r"\s+", " ", s)
    return s.lower()


def _has_value(v: Any) -> bool:
    if v is None:
        return False
    if isinstance(v, str):
        return v.strip() != ""
    if isinstance(v, list):
        return len(v) > 0
    if isinstance(v, dict):
        return len(v) > 0
    return True


def entry_satisfies_fields(entry: Entry, selected_fields: List[str]) -> bool:
    for f in selected_fields:
        if f not in VALID_FIELDS:
            continue
        if not _has_value(getattr(entry, f, None)):
            return False
    return True
def get_missing_fields(entry, selected_fields):
    """
    entry 可能是：
    - dict
    - dataclass / 普通对象（属性访问）
    - pydantic BaseModel（model_dump）
    这里统一用“安全取值”，避免 entry.get 报错。
    """
    def _get_val(obj, key, default=""):
        if obj is None:
            return default

        # dict
        if isinstance(obj, dict):
            return obj.get(key, default)

        # pydantic v2
        if hasattr(obj, "model_dump") and callable(getattr(obj, "model_dump")):
            try:
                d = obj.model_dump()
                if isinstance(d, dict):
                    return d.get(key, default)
            except Exception:
                pass

        # pydantic v1
        if hasattr(obj, "dict") and callable(getattr(obj, "dict")):
            try:
                d = obj.dict()
                if isinstance(d, dict):
                    return d.get(key, default)
            except Exception:
                pass

        # 普通对象属性
        return getattr(obj, key, default)

    miss = []
    for f in selected_fields:
        v = _get_val(entry, f, "")
        if v is None:
            miss.append(f)
        elif isinstance(v, str):
            if not v.strip():
                miss.append(f)
        elif isinstance(v, list):
            if len(v) == 0:
                miss.append(f)
        else:
            # 其他类型：0/False 一般不算缺失，这里不动
            pass

    return miss

# =========================
# JSON Repo（支持坏文件/空文件）
# =========================

def load_json_safely(path: str) -> Dict[str, Any]:
    if not os.path.exists(path):
        return {}
    try:
        if os.path.getsize(path) == 0:
            return {}
    except OSError:
        pass
    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except json.JSONDecodeError:
        return {}
    except Exception:
        return {}


def save_json_atomically(path: str, data: Dict[str, Any]) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    tmp = path + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    os.replace(tmp, path)

class CacheRepo:
    """
    JSON 结构：
      repo[word_norm] = {
        "word_norm": "...",
        "word_display": "...",
        "entries": [EntryDict, ...]
      }
    """

    def __init__(self, path: str):
        self.path = path
        self.data: Dict[str, Any] = load_json_safely(path)
        # 只记录本次真正改动过的 key，避免用旧内存覆盖别人新写入的数据
        self._dirty_keys: set[str] = set()

    def get_group(self, wn: str) -> Optional[WordEntryGroup]:
        raw = self.data.get(wn)
        if not raw:
            return None
        try:
            return WordEntryGroup.from_dict(raw)
        except Exception:
            return None

    def upsert_group(self, group: WordEntryGroup) -> None:
        self.data[group.word_norm] = group.to_dict()
        self._dirty_keys.add(group.word_norm)


    def save(self) -> None:
        """
        上线安全版写回：
        - 跨请求/跨进程加锁：同一时刻只有一个写者
        - 保留 dirty-merge：只写本次改动的 key，降低覆盖风险
        - 仍使用原子写：tmp -> replace，避免半文件
        """
        if not self._dirty_keys:
            return

        lock_path = self.path + ".lock"

        with file_lock(lock_path, timeout=60.0, poll=0.05):
            # 锁内重新读盘：避免用旧内存覆盖别人刚写入的数据
            disk_data = load_json_safely(self.path)

            # 只把本次改动过的 key 写入磁盘数据
            for k in self._dirty_keys:
                if k in self.data:
                    disk_data[k] = self.data[k]

            print(f"[CACHE_WRITE] path={self.path} dirty_keys={len(self._dirty_keys)} lock={lock_path}")
            save_json_atomically(self.path, disk_data)

            # 更新内存快照
            self.data = disk_data
            self._dirty_keys.clear()

# =========================
# 多 entry tie-break（按你需求案）
# =========================

def pick_best_entry(entries: List[Entry]) -> Entry:
    """
    规则：
    1) pos_count 最大优先
    2) tokens 最大优先
    3) 若仍相同，随机选
    """
    if not entries:
        raise ValueError("entries is empty")

    max_pos = max(e.pos_count for e in entries)
    cands = [e for e in entries if e.pos_count == max_pos]

    max_tok = max(e.tokens for e in cands)
    cands2 = [e for e in cands if e.tokens == max_tok]

    return random.choice(cands2)


# =========================
# 写回策略
# =========================

def merge_fill_blanks(dst: Entry, src: Entry, fields: List[str]) -> Entry:
    """USE_CACHE：只填空，不覆盖已有值"""
    for f in fields:
        if f not in VALID_FIELDS:
            continue
        if _has_value(getattr(dst, f, None)):
            continue
        newv = getattr(src, f, None)
        if _has_value(newv):
            setattr(dst, f, newv)
    return dst


def overwrite_entry(dst: Entry, src: Entry) -> Entry:
    """FORCE_OVERWRITE：整条覆盖（保留 norm/original 标识的合理性）"""
    keep_norm = dst.word_norm or src.word_norm
    keep_original = dst.word_original or src.word_original

    out = Entry.from_dict(src.to_dict())
    out.word_norm = keep_norm
    out.word_original = keep_original
    return out


# =========================
# 输出结构
# =========================

@dataclass
class MatchResultItem:
    word_original: str
    word_norm: str
    entry: Entry
    source_stage: str         # global_cache / uploaded_vocab / need_enrich
    missing_fields: List[str]
    chosen_rule: str          # debug 用


# =========================
# MatchService
# =========================

@dataclass
class CacheStores:
    global_cache_path: str
    uploaded_vocab_cache_path: str


class MatchService:
    def __init__(self, stores: CacheStores):
        # print("[STORES_ATTRS]", [a for a in dir(stores) if not a.startswith("_")])
        # print("[STORES_DICT]", getattr(stores, "__dict__", None))
        self.global_repo = CacheRepo(stores.global_cache_path)
        self.uploaded_repo = CacheRepo(stores.uploaded_vocab_cache_path)

    def match_words(
        self,
        words: List[str],
        selected_fields: List[str],
        cache_mode: str = CacheMode.USE_CACHE,
    ) -> List[MatchResultItem]:

        # 防御：过滤非法字段
        selected_fields = [f for f in selected_fields if f in VALID_FIELDS]

        results: List[MatchResultItem] = []

        for w in words:
            w0 = (w or "").strip()
            if not w0:
                continue
            wn = norm_word(w0)

            # 1) global_cache 命中：优先返回“满足字段”的 entry
            g = self.global_repo.get_group(wn)
            if g and g.entries:
                satisfying = [e for e in g.entries if entry_satisfies_fields(e, selected_fields)]
                if satisfying:
                    chosen = satisfying[0] if len(satisfying) == 1 else pick_best_entry(satisfying)
                    results.append(MatchResultItem(
                        word_original=w0,
                        word_norm=wn,
                        entry=chosen,
                        source_stage="global_cache",
                        missing_fields=[],
                        chosen_rule="cache_hit_satisfy",
                    ))
                    continue

                # 命中但不满足：先拿一个 best 当 base，再去 uploaded 看是否更好
                chosen_from_cache = g.entries[0] if len(g.entries) == 1 else pick_best_entry(g.entries)
            else:
                chosen_from_cache = None

            # 2) 查 uploaded_vocab_cache
            u = self.uploaded_repo.get_group(wn)
            if u and u.entries:
                chosen_from_uploaded = u.entries[0] if len(u.entries) == 1 else pick_best_entry(u.entries)

                # 如果 cache 也有 entry：选“缺得更少”的；缺一样则 tie-break
                if chosen_from_cache is not None:
                    miss_cache = get_missing_fields(chosen_from_cache, selected_fields)
                    miss_up = get_missing_fields(chosen_from_uploaded, selected_fields)

                    if len(miss_up) < len(miss_cache):
                        chosen = chosen_from_uploaded
                        chosen_rule = "uploaded_better"
                    elif len(miss_up) > len(miss_cache):
                        chosen = chosen_from_cache
                        chosen_rule = "cache_kept"
                    else:
                        chosen = pick_best_entry([chosen_from_cache, chosen_from_uploaded])
                        chosen_rule = "tie_cache_vs_uploaded"
                else:
                    chosen = chosen_from_uploaded
                    chosen_rule = "uploaded_only"

                miss = get_missing_fields(chosen, selected_fields)

                # match 阶段不写回 global_cache（由 enrich 阶段统一写回）

                if not miss:
                    results.append(MatchResultItem(
                        word_original=w0,
                        word_norm=wn,
                        entry=chosen,
                        source_stage="uploaded_vocab",
                        missing_fields=[],
                        chosen_rule=chosen_rule,
                    ))
                else:
                    results.append(MatchResultItem(
                        word_original=w0,
                        word_norm=wn,
                        entry=chosen,
                        source_stage="need_enrich",
                        missing_fields=miss,
                        chosen_rule=chosen_rule,
                    ))
                continue

            # 3) uploaded 也没命中：need_enrich（构造最小 entry）
            if chosen_from_cache is not None:
                chosen = chosen_from_cache
                chosen_rule = "cache_hit_not_satisfy_no_uploaded"
            else:
                chosen = Entry(word_original=w0, word_norm=wn, source="need_enrich", meta={})
                chosen_rule = "no_hit"

            miss = get_missing_fields(chosen, selected_fields)

            # match 阶段不写回 global_cache
            results.append(MatchResultItem(
                word_original=w0,
                word_norm=wn,
                entry=chosen,
                source_stage="need_enrich" if miss else "global_cache",
                missing_fields=miss,
                chosen_rule=chosen_rule,
            ))

        # match 阶段不写回 global_cache
        # 写回统一由 enrich_service 完成
        pass
        
        return results

    def _write_back(self, wn: str, entry: Entry, selected_fields: List[str], cache_mode: str) -> None:
        if cache_mode == CacheMode.TEMP_ONLY:
            return

        group = self.global_repo.get_group(wn)
        if not group:
            group = WordEntryGroup(word_norm=wn, word_display=entry.word_original, entries=[])

        # 简化策略：global_cache 每个 word 只维护一条“主 entry”（entries[0]）
        if not group.entries:
            group.entries.append(entry)
            self.global_repo.upsert_group(group)
            return

        existing = group.entries[0]

        if cache_mode == CacheMode.FORCE_OVERWRITE:
            group.entries[0] = overwrite_entry(existing, entry)
        else:
            group.entries[0] = merge_fill_blanks(existing, entry, selected_fields)

        self.global_repo.upsert_group(group)


# =========================
# 本地自测入口
# =========================
if __name__ == "__main__":
    # 确保从项目根目录用 -m 跑：
    # python -m services.match_service

    stores = CacheStores(
        global_cache_path=os.path.join("storage", "global_cache.json"),
        uploaded_vocab_cache_path=os.path.join("storage", "uploaded_vocab_cache.json"),
    )

    svc = MatchService(stores)

    # 假设这些词来自 extract_service 的 merged
    words = [
        "organic farming",
        "carbon footprint",
        "genetically modified crops",
        "nonexistent_word_abcxyz",
    ]

    # 假设用户勾选了这些字段（后续 enrich 会补全缺的）
    selected_fields = ["pos_cn", "phonetic_uk", "example", "example_cn", "synonyms"]

    out = svc.match_words(words, selected_fields, cache_mode=CacheMode.USE_CACHE)

    print("\n=== MATCH RESULTS ===")
    for item in out:
        print(f"\nWORD: {item.word_original}  | stage={item.source_stage} | rule={item.chosen_rule}")
        print("missing_fields:", item.missing_fields)
        print("entry.pos_cn:", item.entry.pos_cn)
        print("entry.phonetic_uk:", item.entry.phonetic_uk)
        print("entry.example:", item.entry.example)
